export const languages = {
  ja: '日本語',
  en: 'English',
};

export const defaultLang = 'ja';

export const ui = {
  ja: {
    'nav.home': 'ホーム',
    'nav.research': '研究内容',
    'nav.projects': 'プロジェクト',
    'nav.publications': '業績リスト',
    'nav.members': 'メンバー',
    'nav.access': 'アクセス',
    'nav.news': 'ニュース・ハイライト',
    'hero.title': '大阪大学 実世界知能基盤講座',
    'hero.subtitle': '未来を創る、知能を宿す。',
    'btn.learnMore': '詳しく見る',
    'news.latest': '最新ニュース',
    'about.title': 'コンピュータビジョン講座 (前川研究室) へようこそ',
    'about.text': 'マルチメディア工学専攻コンピュータビジョン講座では、\nコンピュータビジョン・機械学習・最適化などの技術と、\nその大規模情報処理や産業への応用に関する研究を行っています。',
    'announcement.title': 'Announcement',
    'announcement.pubs': 'Recent Publications',
    'announcement.talks': 'Professor Talks',
    'about.welcome': '実世界知能基盤講座（前川研）へようこそ',
    'about.description': '「実世界を理解する人工知能を創る」という目標を掲げ、人間や動物を対象に、マルチモーダルセンサデータから行動・状態・文脈を推定する人工知能の研究を行っています。\n本講座では、IoT・ウェアラブル・バイオロギング、ヒューマン／アニマルセンシング、行動認識・位置推定、エッジAI・組込みAI、Physical AI（フィジカルAI）といった研究分野を横断し、センサ・データ・アルゴリズム・実装を一体として設計することで、実環境で機能する知能基盤の確立を目指しています。',
    'research.themes': '研究テーマ',
    'research.projects': '研究プロジェクト',
  },
  en: {
    'nav.home': 'Home',
    'nav.research': 'Research',
    'nav.projects': 'Projects',
    'nav.publications': 'Publications',
    'nav.members': 'Members',
    'nav.access': 'Access',
    'nav.news': 'News / Highlights',
    'hero.title': 'Real-world Intelligence Laboratory, The University of Osaka',
    'hero.subtitle': 'Innovating Future Intelligence.',
    'btn.learnMore': 'Learn More',
    'news.latest': 'Latest News',
    'about.title': 'Welcome to the Real-World Intelligence Group (Maekawa Lab)',
    'about.welcome': 'Welcome to Real-World Intelligence Lab',
    'about.description': 'We aim to create "Artificial Intelligence that understands the real world." We conduct research on AI that estimates behavior, state, and context from multimodal sensor data, targeting humans and animals.\nOur lab integrates research fields such as IoT/Wearable/Bio-logging, Human/Animal Sensing, Activity Recognition/Positioning, Edge AI/Embedded AI, and Physical AI. By designing sensors, data, algorithms, and implementations as a unified system, we strive to establish an intelligence infrastructure that functions effectively in real-world environments.',
    'research.themes': 'Research Themes',
    'research.projects': 'Research Projects',
    'about.text': 'The Multimedia Engineering — Computer Vision group conducts research on computer vision, machine learning, and optimization, with a focus on large-scale information processing and industrial applications.',
    'announcement.title': 'Announcement',
    'announcement.pubs': 'Recent Publications',
    'announcement.talks': 'Professor Talks',
  },
} as const;
